# 
# Synthesis run script generated by Vivado
# 

set_param simulator.vcsmxInstallPath /eda/synopsys/J-2014.12-SP2
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tfgg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/zxd/work/lvds_xil/lvds_tx/lvds_tx.cache/wt [current_project]
set_property parent.project_path /home/zxd/work/lvds_xil/lvds_tx/lvds_tx.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/zxd/work/lvds_xil/lvds_tx/lvds_tx.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/zxd/work/lvds_xil/lvds_tx/lvds_tx.srcs/sources_1/Verilog_macros/serdes_7_to_1_diff_ddr.v
  /home/zxd/work/lvds_xil/lvds_tx/lvds_tx.srcs/sources_1/Verilog_macros/clock_generator_pll_7_to_1_diff_ddr.v
  /home/zxd/work/lvds_xil/lvds_tx/lvds_tx.srcs/sources_1/Verilog_macros/n_x_serdes_7_to_1_diff_ddr.v
  /home/zxd/work/lvds_xil/lvds_tx/lvds_tx.srcs/sources_1/top5x2_7to1_ddr_tx.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/zxd/work/lvds_xil/lvds_tx/lvds_tx.srcs/constrs_1/new/top5x2_tx.xdc
set_property used_in_implementation false [get_files /home/zxd/work/lvds_xil/lvds_tx/lvds_tx.srcs/constrs_1/new/top5x2_tx.xdc]


synth_design -top top5x2_7to1_ddr_tx -part xc7a100tfgg676-2


write_checkpoint -force -noxdef top5x2_7to1_ddr_tx.dcp

catch { report_utilization -file top5x2_7to1_ddr_tx_utilization_synth.rpt -pb top5x2_7to1_ddr_tx_utilization_synth.pb }
